version: 2

sources:
  - name: ny_data_taxi
    description: >
      Yellow data taxi source
      green data taxi source
      fhv data taxi source
    database: datatalks-411609
    schema: ny_tripdata
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
      - name: fhv_tripdata

models:
  - name: stg_yellow_tripdata

    columns:
      - name: vendor_id
        description: >
          A code indicating the TPEP provider that provided the record.
          1= Creative Mobile Technologies, LLC; 2= VeriFone Inc
      - name: pickup_datetime
        description: >
          The date and time when the meter was engaged.
        # tests:
        #   - unique
        #   - not_null
      - name: dropoff_datetime
        description: >
          The date and time when the meter was disengaged.
        # tests:
        #   - unique
        #   - not_null
      - name: passenger_count
        description: >
          The number of passengers in the vehicle. This is a driver-entered value.
      - name: trip_distance
        description: >
          The elapsed trip distance in miles reported by the taximeter.
      
      - name: ratecode_id
        description: >
          The final rate code in effect at the end of the trip.
          1= Standard rate
          2= JFK
          3= Newark
          4= Nassau or Westchester
          5= Negotiated fare
          6= Group ride
      - name: store_and_fwd_flag`
        description: >
          This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server.
          Y= store and forward trip
          N= not a store and forward trip
      # - name: tripid
      #   tests:
      #     - unique
      #     - not_null
        # description: >  
        #   A unique identifier for each trip
      - name: pickup_locationid
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: dropoff_locationid 
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
  
  - name: stg_green_tripdata

    columns:
      - name: vendor_id
        description: >
          A code indicating the TPEP provider that provided the record.
          1= Creative Mobile Technologies, LLC; 2= VeriFone Inc
      - name: pickup_datetime
        description: >
          The date and time when the meter was engaged.
        # tests:
        #   - unique
        #   - not_null
      - name: dropoff_datetime
        description: >
          The date and time when the meter was disengaged.
        # tests:
        #   - unique
        #   - not_null
      - name: passenger_count
        description: >
          The number of passengers in the vehicle. This is a driver-entered value.
      - name: trip_distance
        description: >
          The elapsed trip distance in miles reported by the taximeter.
      
      - name: ratecode_id
        description: >
          The final rate code in effect at the end of the trip.
          1= Standard rate
          2= JFK
          3= Newark
          4= Nassau or Westchester
          5= Negotiated fare
          6= Group ride
      - name: store_and_fwd_flag`
        description: >
          This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server.
          Y= store and forward trip
          N= not a store and forward trip
      # - name: tripid
      #   tests:
      #     - unique
      #     - not_null
      #   description: >  
      #     A unique identifier for each trip
      - name: pickup_locationid
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationID
              severity: warn
      - name: dropoff_locationid 
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationID

  - name: stg_fhv_tripdata

    columns:
      - name: pickup_datetime
        description: >
          The date and time when the meter was engaged.
        # tests:
        #   - unique
        #   - not_null
      - name: dropoff_datetime
        description: >
          The date and time when the meter was disengaged.
        # tests:
        #   - unique
        #   - not_null  
      - name: pickup_locationid
        description: >
          TLC Taxi Zone in which the taximeter was engaged
      - name: dropoff_locationid
        description: >
          TLC Taxi Zone in which the taximeter was disengaged
      - name: sr_flag
        description: >
          1= the trip was a part of a shared ride; 0= otherwise
      - name: affiliated_base_number
        description: >
          The New York State Department of Motor Vehicles (DMV) issued a unique number to each FHV base
